### ISSUE TITLE
The SHA2 switch doesn't work

### ISSUE THREAD

**Issue by sebastianjena** [TeamWin/Team-Win-Recovery-Project#1050] opened 2017-09-07 21:06 UTC
After the latest update, which switched to SHA2 from MD5, I can't rollback to MD5. In settings there is a "Use SHA2 for hashing" option, which I can't unmark, so I can't choose MD5 again

**Comment by tuxayo** [comment] 2018-10-11 08:53
I have something very similar.
On a Nexus 5 I was on an old version, so only MD5 was possible.
Then I upgraded to v3.2.3-0 and even though "Use SHA2 for hashing" option is ticked, it still uses MD5.

When I untick "Use SHA2 for hashing"
And I switch to another setting tab like the time one
And switch back to the first tab
Then the "Use SHA2 for hashing" is still ticked

**Comment by tuxayo** [comment] 2018-10-11 08:55
@sebastianjena Thanks for opening this issue :)
Do you still have it? And can you reproduce what I have? (2nd paragraph)
Which version? Which phone?

**Comment by CaptainThrowback** [comment] 2018-10-11 11:42
https://gerrit.omnirom.org/32398

**Comment by sebastianjena** [comment] 2018-10-18 09:08
> @sebastianjena Thanks for opening this issue :)
> Do you still have it? And can you reproduce what I have? (2nd paragraph)
> Which version? Which phone?

As the link above says, it was fixed, dunno why this issue is still open, closing it right now

**Comment by tuxayo** [comment] 2018-10-19 12:10
@sebastianjena 
> As the link above says, it was fixed,

The link above was posted **after** my message. I didn't know that at the time of my message.

> dunno why this issue is still open, closing it right now

It depends on each project's issue management. Many leave open until someone having the issue before can confirm that the fix works.

**Comment by bigbiff** [comment] 2018-10-19 12:31
TBH, this can stay open until the next release. It hasn't even been merged yet.

**Comment by tuxayo** [comment] 2019-05-20 12:26
Tested with 3.3.0-0 on Nexus 5 (hammerhead) and the issue is still here.

Does this means that this patch missed a case? https://gerrit.omnirom.org/#/c/android_bootable_recovery/+/32398/
Or that it didn't make into 3.3.0 ?

**Comment by bigbiff** [comment] 2019-05-22 23:44
Tested locally and it works. Please try resetting defaults in TWRP and see if it helps.

**Closed as completed by bigbiff** 2019-05-22 23:44 UTC
