### ISSUE TITLE
TWRP 2.5.0.0 broken backup/restore process on Droid Incredible

### ISSUE THREAD

**Issue by tiny4579** [TeamWin/Team-Win-Recovery-Project#154] opened 2013-04-12 17:02 UTC
I restored a backup taken with TWRP 2.5 on the Droid Incredible.  I'm not sure if the backup or restore were bad but it gave a result similar to this when restoring CM 10.1:

http://forum.xda-developers.com/showpost.php?p=40199358&postcount=172

Below are the recovery.log copied to sdcard using advanced and the recovery.log from backup as recovery-backup.log.

https://dl.dropboxusercontent.com/u/31805083/recovery.log
https://dl.dropboxusercontent.com/u/31805083/recovery-backup.log

**Comment by bigbiff** [comment] 2013-04-16 15:48
Please upload recovery.log after restoring of the backup. The first link doesn't have this information.

**Comment by tiny4579** [comment] 2013-04-27 21:24
Uploaded recovery.log to link above.  This one should be what you needed.  Do you need a new one from the backup as well?

**Comment by tiny4579** [comment] 2013-04-27 21:56
Updated recovery.log from CM10.1 backup that still failed to restore on TWRP 2.4.4.0.

**Comment by bigbiff** [comment] 2013-04-27 22:18
How big are the files?

**Comment by tiny4579** [comment] 2013-04-27 23:55
Well, data is max 750MB due to the fact that the Inc only supports 750MB
/data.  I think the issue is related to /datadata.  /datadata is actually a
yaffs2 image so it should be treated as such and the log looked like it was
trying to untar a yaffs2 filesystem image.  The backup was about 80MB I
want to say.  I deleted it due to trying to manually recover the partition
using flash_image but typing dump_image and not realizing my mistake before
too late so I can't get the actual size now.

Either way, even on TWRP 2.4.4.0 I couldn't restore the backup properly.

**Comment by Mike-Ferretti** [comment] 2013-04-29 23:13
I am having this same exact issue. Made a backup and it was successful. Later on, while trying to restore it, the part where data was restoring caused it to fail. Any idea?

**Comment by kasperhettinga** [comment] 2013-05-27 17:24
I also have a broken /datadata backup/restore. Looking at the recovery log taken during the backup, it already goes wrong during the backup of the datadata partition:
https://www.dropbox.com/s/bkygto4658w2x42/recovery.log

BTW, should the yaffs2 partition be backupped as an image in stead of files?

This is for galaxysmtd.

**Comment by varunchitre15** [comment] 2013-05-28 13:26
We have similar issue but in a more fatal way on a phone named Micromax A110 Canvas 2
Users have confirmed that Back/Restore works well in 2.4.x but it doesn't on 2.5.x
The restore completes successfully but phone doesn't boot at all after restoring, there is no such issue with 2.4.x according to reports.

**Comment by bigbiff** [comment] 2013-05-28 13:38
kasperhettinga: looks like you have some errors in your recovery.fstab you need to fix. Emmc isn't being seen because of an error in there.

Also please post the restore log. We recreate the yaffs partition and then untar onto the filesystem

 varunchitre15: Please post backup and restore logs.

**Comment by kasperhettinga** [comment] 2013-05-28 17:29
The restore log:
https://www.dropbox.com/s/x9fynx5sa3v1xg8/restore.log

Phone boots, but goes crazy.

Emmc is not seen, because it is not there :) It is the mount point of the optional SD card (galaxysmtd has /sdcard as mount point for internal sd, and /emmc for (removable) external sd).

/datadata backup&restore was still functional until 2.5.0.0

**Comment by kasperhettinga** [comment] 2013-05-30 14:07
I just started removing patches one-by-one from new-to-old to see when the problem would be solved, knowing that 2.4.4.0 had functional backup/restore. After removing this patch:
https://github.com/TeamWin/Team-Win-Recovery-Project/commit/3263e9260c2ef4d7a5b7759dc18010b179fb3ad7
(so when I was almost back at 2.4.4.0), backup/restore of /datadata starting working again.

**Comment by Dees-Troy** [comment] 2013-06-19 20:06
This patch set should fix the problem:
http://review.teamw.in/#/c/611/
It will be part of our upcoming 2.6 release. If you get a chance please test it out and let me know. Thanks.

**Comment by kasperhettinga** [comment] 2013-06-19 21:49
Just build a new kernel with TWRP2.5.0.0 and the patch you mentioned. Then backup & restored the data partition. And all worked fine. Thanks a lot!

**Comment by Alxoom33** [comment] 2013-06-20 02:03
Dear Troy,
Thank you for your response and email, regarding the patch.  Unfortunately,
compiling the patch and modifying my TWRP recovery is beyond my level of
ability without someone walking me through it step-by-step.  Please let me
know if you or someone else has posted a flashable zip file or  kernal that
I may use. Otherwise, I will need to wait for TWRP 2.6 for the Samsung S4.
Thanks again,
Alan

**Closed as completed** 2018-08-13 14:47 UTC
