### ISSUE TITLE
twrp 2.8.6.0 fails to mount lollipop encrypted partition

### ISSUE THREAD

**Issue by zman0900** [TeamWin/Team-Win-Recovery-Project#358] opened 2015-03-28 00:39 UTC
Device: nexus 4 (mako)

TWRP 2.8.6.0 fails to mount the /data partition when it is encrypted.  It never prompts for a password and the log shows an error similar to "unable to find crypto footer".  Downgrading to 2.8.5.2 allows the partition to be decrypted just fine.  

Some possibly relevant info: Cyanogenmod 12 (nightly from 2015-03-26) was the OS used to originally encrypt the partition.  At the time of encryption, a password was set.  After it was done, I changed that to a pin.  Then I used the app [Cryptfs Password](https://play.google.com/store/apps/details?id=org.nick.cryptfs.passwdmanager) to change the encryption back to a more complicated password but leave the pin for the lock screen.  Android boots with no problems in this configuration.

**Comment by zman0900** [comment] 2015-03-28 23:54
Same issue with my nexus 7 2013 (flo).  For it, I installed stock android 5.0.2, set a lock screen password, then encrypted.  I did not even install the Cryptfs Password app.  For this device, I had to downgrade twrp all the way to version 2.8.2.2 to be able to unlock the encrypted partition.

**Comment by fprietog** [comment] 2015-03-29 09:16
Just to confirm that encryption is broken in TWRP for mako (nexus 4) v. 2.8.6.0.

It usually happens with every new TWRP version published for this mobile.

Here is the last_log: http://pastebin.com/EnVTEFPc

**Comment by jfeise** [comment] 2015-03-30 15:26
And another voice. Running CM12 nightlies on Nexus 4, with encrypted /data. TWRP 2.8.6.0 doesn't prompt for the password at all.
Reverted to 2.8.5.2.

**Comment by ghost** [comment] 2015-04-05 20:44
Same
Nexus 4 CM12

**Comment by cyanfr** [comment] 2015-04-05 22:07
same
Nexus 7 2013 LTE (deb) CM12

**Comment by marvinandro** [comment] 2015-04-06 22:08
CM12 nighties on bacon (OPO) - also broken decrypt

**Comment by mydewji** [comment] 2015-04-14 16:47
CM12S (recently released) - also broken decrypt

**Comment by Icehunter** [comment] 2015-04-15 05:26
OxygenOS with pattern lock also is broken.

**Comment by SnowGabe** [comment] 2015-04-21 18:44
I have this issue on TWRP 2.8.5.0. HTC One M7.

**Comment by Diapolo** [comment] 2015-04-22 12:14
TWRP on ks01lte with CM12 nightly is also not ablte to access encrypted /data :-/.

**Comment by dkaufman-irise** [comment] 2015-04-27 23:21
Oneplus One, cyanogenmod 12S latest, TWRP 2.8.6.0, TWRP fails to mount encrypted data, attempted just now.

**Comment by zman0900** [comment] 2015-04-28 07:54
I just got a Moto X 2014, and interestingly enough, TWRP 2.8.6.0 actually is able to mount the encrypted partition on it.

**Comment by phaseburn** [comment] 2015-04-28 12:37
The issue with TWRP failing to decrypt data partitions on *some* 5.0+ devices is pretty straight forward. Here's why.

Some devices (Nexus 4, 5, 6, 7 (2013), and 9, but not 7 (2012) and 10, The OnePlus One, HTC One...) use a hardware keymaster. This little chip stores the encryption keys for the data partition as of Android 5.0, and, TWRP can not access them because it doesn't support that. Primarily, this is only on Qualcomm devices. There is some proprietary library that retrieves it.

The Moto X isn't using that. I'm not sure if it has the hardware keymaster in it or not, but, it isn't being used if it does (and your TWRP is working, obviously). AOSP was modified in 5.0 to support this, if present, but some ROM vendors (OEMs, as well as custom ROM teams) could disable the support for the hardware keymaster if they wished. There is a performance penalty for doing so, but it isn't exceptionally high. There's a lot of security concerns for doing so, IMO. I explored the option for CarbonROM a while ago (as I have pretty much all the affected devices I mentioned above).

The truth is, TWRP doesn't support encrypted data if a hardware keymaster is used, or if full blown hardware encryption is used (which some devices support, also, like the OnePlus One). TWRP authors are working on the first challenge (Dees-Troy has stated he has it working for him, actually, in a limited regard), and haven't commented about the 2nd other than "It's on the list". So, this is why TWRP works for some devices with encrypted data, and, not for others.

For the sake of keeping the issue tracker relevant, please lets avoid posting "me too!" comments. If you wish to follow the progress of an issue, there's a subscribe button. The issue has a known root cause, and they are working on resolving that. It's a big issue for a lot of users at the moment. Thx!

**Comment by ghost** [comment] 2015-04-28 12:56
phaseburn, only new version of TWRP can't decrypt. So we continue using CM12.1 and 2.8.5.2.

**Comment by fprietog** [comment] 2015-04-28 13:03
@phaseburn, in having the problem with my Nexus 4 only with the latest TWRP version 2.8.6.0. The previous version 2.8.5.2 works flawlessly with the same device. So your theory is not correct.

**Comment by phaseburn** [comment] 2015-04-28 13:10
Ahh, it's only the 2.8.6.0 version. Ok, my information wasn't accurate, my bad. We're having the same issue on other devices, where that was in fact what was going on. Good to see it doesn't apply here.

**Comment by fprietog** [comment] 2015-05-17 02:59
New TWRP 2.8.6.1 for Mako fixes the decryption problem :)

Unfortunately it has new/old problems like showing all the screen moved to the right (because there is an unnecesary offset to center the screen).

I'll open another bug :(

**Comment by Peetz0r** [comment] 2015-08-28 07:19
I have this problem with CM12.1 nigtly and 2.8.7.0...
It does ask me foir my unlock pattern but it fails to decrypt.
Device is a Moto G (falcon).

**Comment by mattjanicki** [comment] 2015-09-12 02:36
Same issue with CM 12.1 nightly and TWRP for the 2014 Moto X Pure Edition (victara).  I encrypted it when it was stock, installed CM through recovery (PIN worked fine for decrypting at the time), set everything up, and went to check out my recovery but suddenly my PIN doesn't work.  Not sure what happened:-/

**Comment by JannF** [comment] 2015-10-04 10:04
Same issue with Oneplus Two with TWRP 2.8.7.0 .
Can't access the /data partition and therefore can't get OTAs or Backups.

**Comment by thesleepydoc** [comment] 2015-10-04 10:28
Same issue here with LG G3 d851 Tmo version running Blisspop 4.0.2 from 9/24 tried to update to 9/30 after encryption.  There was no pin prompt for twrp and I am unable to mount data running 2.8.7.0. I'm thinking the only option is ADB at this point. Just gives unable to mount error. Other functions work fine unless they require data partition, e.g fix permission.

**Comment by licaon-kter** [comment] 2015-10-13 09:02
Just to chime in, 2.8.7.0, stock versions with issue:
- LG G3 ( D855 )
- Sony Xperia Z3 ( D6603 )

**Comment by alistairbill** [comment] 2015-10-23 08:44
Same issue here with Sony Xperia Z3 Compact (D5803) / TWRP 2.8.7.0
TWRP asks me for a password (I have a pin code) but the partition is not unlocked if I enter it.

**Comment by huettenhain** [comment] 2015-11-06 07:11
I have an LG G3 (D855) running CM 12.1-20151017-NIGHTLY-D855. Data partition is encrypted with a password and my screen security is a PIN, same as @zman0900. I went through all the TWRP versions that I could find on short notice (2.8.3.0, 2.8.4.0, 2.8.5.0, 2.8.6.0 and 2.8.7.0) and none of them can read the data partition, same errors exactly as @zman0900 reported.

**Comment by rotanid** [comment] 2015-12-21 19:31
can confirm what lichtkegel is experiencing with CM 12.1-20151117-SNAPSHOT-YOG7DAO1K8-d855

**Comment by thesleepydoc** [comment] 2015-12-21 19:36
Not sure if anyone else has heard this, but I saw on the One plus forum
that the TWRP is aware of the issue, but has given up on trying to find a
solution after multiple failed attempts.

**Comment by Micha-Btz** [comment] 2015-12-22 11:30
i am affected too. Sony Z1 Compact twrp 2.8.7.0
CM12.1 20.12.2015 real recovery

**Comment by DigiAngel** [comment] 2016-03-02 15:17
Confirming this with LG G3 CM 12.1-20151117-SNAPSHOT-YOG7DAO1K8-d855 with 2.8.7.0 and even 3.0

**Comment by huettenhain** [comment] 2016-09-01 15:14
Hey everyone! The following fork of TWRP claims to have fixed the crypto issue for d855:
http://forum.xda-developers.com/lg-g3/development/recovery-twrp-3-0-0-0-t3309475
I have not tried it, but maybe it's worth checking out.

**Comment by BoBeR182** [comment] 2017-01-04 07:45
Sony Z3 D6603 not possible to decrypt data yet. Just tried with TWRP 3.0.2.0

**Comment by nailyk-fr** [comment] 2017-01-04 10:58
@BoBeR182 there is no official release for z3. Please contact your twrp dev on xda.

**Comment by bigbiff** [comment] 2018-08-19 18:53
Can't manage every device in one bug request so closing.

**Closed as completed by bigbiff** 2018-08-19 18:53 UTC
