### ISSUE TITLE
Terminal error? 

### ISSUE THREAD

**Issue by zimlokks** [TeamWin/Team-Win-Recovery-Project#107] opened 2013-02-25 17:18 UTC
Hey thanks for the best recovery ever, small bug when opening the teminal it doesn't allow me to actually see a folder to select. newest recovery released droid inc

**Comment by bigbiff** [comment] 2013-02-28 14:47
Can you take a camera shot of this?

**Comment by Dees-Troy** [comment] 2013-03-18 16:43
Closing due to no follow-up from zimlokks and unable to reproduce.

**Closed as completed by Dees-Troy** 2013-03-18 16:43 UTC
