### ISSUE TITLE
Cannot Decrypt

### ISSUE THREAD

**Issue by sureguy** [TeamWin/Team-Win-Recovery-Project#293] opened 2014-07-28 02:23 UTC
Tried the following on SGS3 running CM11-20140708-SNAPSHOT-M8 (4.4.4)+
TWRP v2.6.3.0 [d2can] - Unable to decrypt
TWRP v2.7.0.0 [d2can] - Unable to decrypt
TWRP v2.7.1.0 [d2can] - Unable to decrypt

Copied and pasted from #247 which is closed.  I'm experiencing the same issue.

**Comment by wertarbyte** [comment] 2014-07-31 09:53
I have the same issue here with i9300 - it's a real showstopper :-/

**Comment by jgus** [comment] 2014-08-04 05:21
Ditto on d2spr. :-(

**Comment by alextoombs** [comment] 2014-08-04 18:59
+1

**Comment by kasiub** [comment] 2014-08-04 18:59
I have the same issue with cyanogen M8 on GT-I9300...

**Comment by BossLX** [comment] 2014-08-21 03:29
+1

**Comment by jgus** [comment] 2014-09-17 02:27
Still an issue with TWRP v2.8.0.1 on d2spr

**Comment by Alphakilo** [comment] 2014-10-08 15:11
Still an issue on my i9300, using TWRP 2.8.0.1

The workaround posted in #247 by @boeleman no longer works, due to the vdc binaries missing.

**Comment by Muellersirch** [comment] 2014-10-13 14:30
I am having this issue on my HTC m8 (Sprint).  I was previously unable to find a decrypt option (several versions, up to the current official release).  After working with Captain_Throwback, we got the option to decrypt to show up, but it does not accept the password.  I am still using the original password that I set the encryption up with, and have no issues decrypting when booting into the system.  I am currently running the CM11 nightly from 10/10.

**Comment by brbsix** [comment] 2014-10-15 04:02
I had this same issue a while back on my d2lte/d2tmo after upgrading to 4.4.2 and it drove me nuts. Not one of the TWRP binaries available would properly decrypt /data in recovery. It would prompt for the password and fail.

I don't recall precisely what I did, but I ended up having to download all the CM and TWRP sources, tweak a few things, then compile the recovery myself. I'm not sure why all of the public binaries failed to handle decryption properly, but at least the source is fully functional.

**Comment by sureguy** [comment] 2014-10-15 04:53
While that provides some hope, without steps to correct the problem we're
left with hope, not a solution.  Not your fault, at all - and thanks for
taking the time to offer your input.

I just wish TWRP devs would chime in with a "we know it's broken and are
looking into it" or "we know it's broken and can't/don't care to fix it"

On Wed, Oct 15, 2014 at 12:02 AM, brbsix notifications@github.com wrote:

> I had this same issue a while back on my d2lte/d2tmo after upgrading to
> 4.4.2 and it drove me nuts. Not one of the TWRP binaries available would
> properly decrypt /data in recovery. It would prompt for the password and
> fail.
> 
> I don't recall precisely what I did, but I ended up having to download all
> the CM and TWRP sources, tweak a few things, then compile the recovery
> myself. I'm not sure why all of the public binaries failed to handle
> decryption properly, but at least the source is fully functional.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TeamWin/Team-Win-Recovery-Project/issues/293#issuecomment-59154999
> .

## 

Simon Bolduc

**Comment by Alphakilo** [comment] 2014-10-17 14:02
So you could provide a patch?

2014-10-15 6:02 GMT+02:00 brbsix notifications@github.com:

> I had this same issue a while back on my d2lte/d2tmo after upgrading to
> 4.4.2 and it drove me nuts. Not one of the TWRP binaries available would
> properly decrypt /data in recovery. It would prompt for the password and
> fail.
> 
> I don't recall precisely what I did, but I ended up having to download all
> the CM and TWRP sources, tweak a few things, then compile the recovery
> myself. I'm not sure why all of the public binaries failed to handle
> decryption properly, but at least the source is fully functional.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TeamWin/Team-Win-Recovery-Project/issues/293#issuecomment-59154999
> .

## 

PGP Public Key:
56AFB56B @ pgp.mit.edu

http://pgp.mit.edu/pks/lookup?op=get&search=0x42F0C03156AFB56B

**Comment by generalmx** [comment] 2014-11-23 20:58
Duplicate of #247, and I can confirm the workaround @boeleman specified there does work on my Sprint SGS3 using latest Philz Touch CWM and encrypted by AOSP KitKat 4.4.x.

**Comment by sureguy** [comment] 2014-11-24 02:38
So the solution is to use another product, and some weird workaround?  That's not a solution.  #247 is closed and the problem still exists.  Perhaps now that decryption no longer works on Lollipop on Nexus devices it will get looked at.

**Comment by jgus** [comment] 2015-02-02 15:35
Hallelujah!

Upgraded to TWRP 2.8.4.0, and decryption now appears to be _working_! (d2spr w/ CM-11-M12)

**Comment by system7ltd** [comment] 2018-06-05 22:56
Downgraded from 3.2.1-1 to 2.8.4.0.  Both 3.2.1-1 and 2.8.4.0 confirmed NOT working.

**Closed as completed** 2018-08-13 18:15 UTC
