### ISSUE TITLE
question: 3.4.x build for blueline

### ISSUE THREAD

**Issue by brainchild0** [TeamWin/Team-Win-Recovery-Project#1605] opened 2021-04-12 20:35 UTC
Are official builds planned for blueline (Pixel 4) for versions greater than 3.3.x?

**Comment by bigbiff** [comment] 2021-04-12 22:01
This is not a bug for TWRP so closing. It depends on someone who has a blueline that can update the device tree.

**Closed as completed by bigbiff** 2021-04-12 22:01 UTC

**Comment by brainchild0** [comment] 2021-04-13 22:24
Is the matter only one of someone who owns the device testing a build?

(Where is a more appropriate location for this discussion?)

**Comment by brainchild0** [comment] 2021-04-23 22:39
In any case, it certainly would be nice to see a build for this device, which is relatively recent, and still in use.
