### ISSUE TITLE
TWRP 2.8.4.0 touchscreen not responding then reboots on the Bacon Issue fixed with 2.8.4.1

### ISSUE THREAD

**Issue by bombadier** [TeamWin/Team-Win-Recovery-Project#330] opened 2015-01-14 11:21 UTC
On the latest version the touchscreen does not respond and after a couple of seconds the recovery reboots,
I got the last_log which I hope will be of some use in troubleshooting this issue

Last_Log
http://pastebin.com/dtBa2TCj

XDA Developers Thread
http://forum.xda-developers.com/showthread.php?t=2766186&page=62#post58165099

Some users are reporting that everything works but seems like for the majority its broken

**Comment by jfeise** [comment] 2015-01-14 14:15
Exact same issue here.

**Comment by MarceloLagos** [comment] 2015-01-14 17:32
Can confirm.
OnePlus One 64G
- Installed 2.8.4.0 over 2.8.3.0 with TWRP app.
  -- Recovery starts but doesn't respond to touches. About 5s later, it reboots.
- Installed 2.8.4.0 using .img file from TWRP site using adb and fastboot.
  -- Same issue.
- Installed 2.8.3.0 using TWRP app
  -- Works normal again.

**Comment by jfeise** [comment] 2015-01-14 18:54
A workaround that Dees-Troy gave on irc:
Install 2.8.3.0. Disable MTP in the UI. Reboot from the TWRP UI to save the config. Install 2.8.4.0.
Works for me.

**Comment by bombadier** [comment] 2015-01-14 19:03
Tried the above method,managed to install but after rebooting into recovery with it plugged in, back to non responsive touchscreen then a reboot, guess will have to wait on a fix

**Comment by AncientLord** [comment] 2015-01-14 20:38
With newly released 2.8.4.0, touch screen is not working anymore and phone reboots. Moreover the reported CPU temperature is not right. It's somewhat 10 degrees higher than reported by 2.8.3.0. Any fix will be appreciated. I am on stock CM11s with Build Number XNPH44S.

**Comment by RickyZiegahn** [comment] 2015-01-14 22:22
Also have this issue, I can click for half a second after it loads, then it becomes unresponsive and reboots shortly after.

**Comment by WEM97** [comment] 2015-01-15 02:42
Confirmed here too.

**Comment by jfeise** [comment] 2015-01-15 05:06
2.8.4.1 is out, fixing this problem. I tried it before the final release, helping Dees_Troy test it.

**Comment by bombadier** [comment] 2015-01-15 10:25
Can confirm 2.8.4.1 is working and the issues have been fixed,this can now be closed

**Comment by Dees-Troy** [comment] 2015-03-05 16:24
Closing since the issue is fixed.

**Closed as completed by Dees-Troy** 2015-03-05 16:24 UTC

**Comment by Darkvater** [comment] 2016-10-06 00:34
Have the same problem on 3.0.2.0 on a xiaomi mi4c. The phone doesn't reboot though, just stuck on the swipe part.
