### ISSUE TITLE
Device request

### ISSUE THREAD

**Issue by KhanMohamed** [TeamWin/Team-Win-Recovery-Project#1463] opened 2019-05-21 01:14 UTC
TWRP custom recovery for Allcall Mix 2 please

**Comment by CaptainThrowback** [comment] 2019-05-21 12:13
This is not a place for device requests. Please close.

**Comment by KhanMohamed** [comment] 2019-05-21 12:15
Oh sorry my bad, by the way I found a 3.2.1 version but In the Russian servers (website and cloud) so... I got through. Thanks anyways have a nice day

**Comment by bigbiff** [comment] 2019-05-21 12:17
Closing due to not a bug.

**Closed as completed by bigbiff** 2019-05-21 12:17 UTC
