### ISSUE TITLE
Can't decrypt /data partition on Galaxy S3 (i9300) on device encrypted with CM11

### ISSUE THREAD

**Issue by ghost** [TeamWin/Team-Win-Recovery-Project#263] opened 2014-03-09 13:08 UTC
Hi I installed TWRP 2.7 on my Galaxy S3 (i9300) which has been encrypted using CM11 nightlies.

TWRP 2.7 can't seem to be able to decrypt the /data partiton. I keep getting a "Decryption failed" message whenever I enter the decryption password.

Here are the relevant recovery.log lines:

```
I:Copying file /cache/recovery/log to /cache/recovery/last_log
I:Is encrypted, do decrypt page first
I:Switching packages (TWRP)
I:Set page: 'decrypt'
I:Set page: 'trydecrypt'
I:Unable to mount '/external_sd'
I:Actual block device: '', current file system: 'vfat'
Warning: crypto footer minor version 2, expected 0, continuing...
Error temp mounting decrypted block device
E:Failed to decrypt data.
I:Set page: 'decrypt'
I:Set page: 'main'
I:Set page: 'clear_vars'
I:Set page: 'main2'
I:Set page: 'main'
I:Set page: 'clear_vars'
I:Set page: 'main2'
I:Cannot load settings -- encrypted.
I:Switching packages (TWRP)
I:Cannot find file /nobrightness
I:Set page: 'mount'
I:Set page: 'decrypt'
I:Set page: 'trydecrypt'
I:Unable to mount '/external_sd'
I:Actual block device: '', current file system: 'vfat'
Warning: crypto footer minor version 2, expected 0, continuing...
Error temp mounting decrypted block device
E:Failed to decrypt data.
I:Set page: 'decrypt'
I:Set page: 'trydecrypt'
I:Unable to mount '/external_sd'
I:Actual block device: '', current file system: 'vfat'
Warning: crypto footer minor version 2, expected 0, continuing...
Error temp mounting decrypted block device
E:Failed to decrypt data.
I:Set page: 'decrypt'
I:Set page: 'main'
I:Set page: 'clear_vars'
I:Set page: 'main2'
```

Seem to me like the issue is caused by:

```
Warning: crypto footer minor version 2, expected 0, continuing...
```

[Full recovery.log file](https://drive.google.com/file/d/0B1p-AmK_Z7DAeWxBZEpNMGhNSWM/edit?usp=sharing)

The following issues seem to be related:
Issue #186 
Issue #187 
Issue #188 
Issue #190

**Comment by brimstone** [comment] 2014-03-09 19:13
I get the same problem with 2.7.0.0 on a t999.

**Comment by mioux** [comment] 2014-03-10 06:52
Same problem with 2.6.3.0, also tried 2.7.0.0

**Comment by MWisBest** [comment] 2014-03-22 05:35
VZW Galaxy Nexus here... 2.6.3.0 through 2.6.3.2 work fine for decryption, 2.7.0.0 is a no-go.

**Comment by generalmx** [comment] 2014-04-04 18:19
Same problem on a d2spr SGS3 here. It seems there may be a version mismatch on TWRP decryption related to initially encrypting on a KitKat (4.4.x) ROM?

**Comment by MWisBest** [comment] 2014-04-04 18:31
I did an initial encryption on KitKat. The problem for the Galaxy Nexus is that the TWRP build configuration for it has "TW_INCLUDE_CRYPTO := true", however to support anything Jellybean or higher it has to be "TW_INCLUDE_JB_CRYPTO := true". After changing and building TWRP myself it works just fine again.

**Comment by ghost** [comment] 2014-04-04 18:35
Can someone compile TWRP for i9300 with the fix above? I'd like to try it but I don't have a build environment setup on my laptop.

**Comment by MWisBest** [comment] 2014-04-04 18:40
I checked and it looks like i9300 has TW_INCLUDE_JB_CRYPTO := true, and had it at the time of any 2.7.0.0 build, so that's not the problem it seems. However, it doesn't look like it has TW_INCLUDE_CRYPTO_SAMSUNG, I wonder if that's the problem?

**Comment by codemonkee** [comment] 2014-07-17 00:16
Tried the following on SGS3 running CM11-20140708-SNAPSHOT-M8 (4.4.4)
TWRP v2.6.3.0 [d2can] - Unable to decrypt
TWRP v2.7.0.0 [d2can] - Unable to decrypt
TWRP v2.7.1.0 [d2can] - Unable to decrypt

**Comment by ghost** [comment] 2014-07-30 18:18
Can someone give us an update on the progress of this issue?

**Comment by wb7** [comment] 2014-08-17 15:51
I have the same issue with two i9300, so I am interested in a solution, too.

**Comment by Brotinger** [comment] 2014-10-31 15:22
TWRP v2.8.1.0 [i9300] - Unable to decrypt

**Comment by leosala** [comment] 2014-11-16 08:30
TWRP 2.8.1.0 on an i9300 and unable to decrypt...

**Comment by terrypearson** [comment] 2014-11-18 18:13
Using full disk encryption on Pacman Rom Sprint S3...
2.6.3.0 [d2spr] - Failed to decrypt data
2.6.3.1 [d2spr] - Failed to decrypt data
2.8.1.0 [d2spr] - Failed to decrypt data

TWRP is using the wrong decryption algorithm. It would be so very helpful to get this fixed. This one feature (if working) is the biggest advantage over Clockwork recoveries. Please update the recovery to support non-touchwiz rom full disk encryption on the S3!

**Comment by JaBecker** [comment] 2014-11-21 10:13
Same problem here:

TWRP 2.8.1.0 on an i9300 and cm-11-20141117-NIGHTLY-i9300.zip

**Comment by generalmx** [comment] 2014-11-23 20:59
Duplicate of #247, and I can confirm the workaround @boeleman specified there does work on my Sprint SGS3 using latest Philz Touch CWM and encrypted by AOSP KitKat 4.4.x.

**Comment by Brotinger** [comment] 2014-12-23 10:30
TWRP 2.8.3.0 on CM11M12 on i9300: It works. Thanks.

**Closed as completed** 2018-08-13 18:07 UTC
