### ISSUE TITLE
Not being able to flash AROMA zip on treble A/B devices like OP6 or U12+ (imagine)

### ISSUE THREAD

**Issue by jeanrivera** [TeamWin/Team-Win-Recovery-Project#1291] opened 2018-08-11 12:29 UTC
while trying to flash any AROMA GUI Installer embedded zip for example a ROM or OpenGapps, TWRP just freezes but adb commands still work it looks like a graphics rendering issue because it doesn't even get to the splash part of any zip with AROMA GUI I can provide logs if needed,

I know AROMA is an abandoned project but some of the ROM devs still use it for personal customizations on custom ROMs like Team Venom, LeeDroid, etc.... & Kernels like Elemental X

[recovery (4).log](https://github.com/TeamWin/Team-Win-Recovery-Project/files/2280231/recovery.4.log)

**Comment by CaptainThrowback** [comment] 2018-08-11 12:38
The recovery log has no errors. If the issue you're having is an AROMA issue, then you need to provide an AROMA log. Also, AROMA issues aren't TWRP issues, so please post this issue to the AROMA github and close this one.

Additionally, you state "treble A/B" devices, so does that mean that A/B devices that don't support Project Treble are unaffected? Either way, I don't think this issue belongs here, at least not without any quantifiable proof that it is a TWRP issue. If TWRP doesn't have issues flashing anything else, then it seems logical to assume that the issue is with the outdated AROMA code.

**Comment by jeanrivera** [comment] 2018-08-11 12:50
I do not have access to many devices or have the knowledge what devices are A/B without treble support, I understand your point completely and I respect you so much, but I think it would be wise to leave this issue open at least for couple of days to see if we can get more feedback on the issue from other users having the error, let be hones AROMA being an abandoned project the issue there will not get so much attention than it could get here, I understand it is more related to AROMA than TWRP but that project was made to flash zips with customizations on while recovery like TWRP, since all other recovery projects are also abandoned and TWRP is the standard nowadays,  if you don't agree or think it is a good idea, please let me know and I'll close it

**Comment by CaptainThrowback** [comment] 2018-08-11 12:51
We can leave it open for a few days and see if anyone else posts here with the same issue (and hopefully some logs), but if not, there's nothing to do but close it. If you can provide an AROMA test zip or something a dev can use to test this locally, that might also be helpful.

**Comment by jeanrivera** [comment] 2018-08-11 13:01
here is a test zip

I just fixed the previous one was broken
[aroma_installer-3.00b1.zip](https://github.com/TeamWin/Team-Win-Recovery-Project/files/2281309/aroma_installer-3.00b1.zip)

**Comment by jeanrivera** [comment] 2018-08-11 13:06
another test zip with a more stable version of aroma 
[aroma-2.70RC2.zip](https://github.com/TeamWin/Team-Win-Recovery-Project/files/2280254/aroma-2.70RC2.zip)

**Comment by jeanrivera** [comment] 2018-08-12 19:56
this was taken with a debug recovery
aroma_installer-3.00b1.zip
[recovery.log](https://github.com/TeamWin/Team-Win-Recovery-Project/files/2281289/recovery.log)
[logcat.txt](https://github.com/TeamWin/Team-Win-Recovery-Project/files/2281290/logcat.txt)

**Comment by jeanrivera** [comment] 2018-08-12 20:08
this was taken with a debug recovery also
aroma-2.70RC2.zip
[recovery.log](https://github.com/TeamWin/Team-Win-Recovery-Project/files/2281295/recovery.log)
[logcat.txt](https://github.com/TeamWin/Team-Win-Recovery-Project/files/2281296/logcat.txt)

**Comment by CaptainThrowback** [comment] 2018-08-12 21:11
If you looked at those logs, you'll see there's nothing in them related to any errors with AROMA.

**Closed as completed** 2018-08-20 05:12 UTC

**Comment by jeanrivera** [comment] 2018-08-20 05:13
There is apparently no point in trying to fix this anymore no one is interested in it anymore.... and the original project is dead
