### ISSUE TITLE
TWRP for h815 2.8.7.0 and 2.8.6.1 can NOT decrypt LG G4 H815

### ISSUE THREAD

**Issue by FSPQR** [TeamWin/Team-Win-Recovery-Project#477] opened 2015-08-13 21:51 UTC
Hi,
i have a stock rom LG G4 H815 with software V10c (was the same in 10b) and encypted sd card + encrypted data.
I can fastboot boot perfectly in TWRP and I do get a prompt for password entry. But it doesn't matter what I enter wrong password or correct one (I do unlock my phone several times a day and enter it while booting, it IS the correct password, TWRP tells me: "Password Failed, Please Try Again". Console output is:
Updating partition details...
...done
E:Unable to mount storage.
Full SELinux support is present.
E:failed to decrypt data.
E:failed to decrypt data.
E:failed to decrypt data.

It was talked about this error in here to:
http://forum.xda-developers.com/g4/help/twrp-2-8-7-0-2-8-6-1-decrypt-lg-g4-h815-t3171040

Any chance this can be fixed?

**Comment by davidtorcivia** [comment] 2015-11-19 02:03
This bug is still present as of posting. 

There is now a $20 bounty for the fix available on Bounty Source here: https://www.bountysource.com/issues/25741595-twrp-for-h815-2-8-7-0-and-2-8-6-1-can-not-decrypt-lg-g4-h815

**Comment by baudlord** [comment] 2016-04-02 13:51
TWRP 3.0.1-0 can't decrypt (CyanogenMod 13) either.

**Comment by steadfasterX** [comment] 2016-05-28 10:32
Running CM13 and I tested the following TWRP versions (FLASHED not fastboot boot!)
- twrp-3.0.2-0-h815.img 
- twrp-3.0.1-0-h815.img  
- twrp-3.0.0-0-h815.img  
- twrp-2.8.7.0-h815.img  
- twrp-2.8.6.1-h815.img  

None of them can decrypt my fully encrypted device..

**Comment by steadfasterX** [comment] 2016-05-28 10:57
recovery.log when I try to decrypt over the GUI (twrp 3.0.2-0):

When /system is **not** **mounted**:

> I:Set page: 'trydecrypt'
> I:operation_start: 'Decrypt'
> crypt_ftr->fs_size = 48627712
> Using scrypt with keymaster for cryptfs KDF
> could not find any keystore module
> Failed to init keymaster
> Signing failed
> kdf failed
> failure decrypting master key
> Failed to decrypt master key
> crypt_ftr->fs_size = 48627712
> Using scrypt with keymaster for cryptfs KDF
> could not find any keystore module
> Failed to init keymaster
> Signing failed
> kdf failed
> failure decrypting master key
> Failed to decrypt master key
> Failed to decrypt data.
> I:Set page: 'decrypt'
> I:operation_end - status=1

When /system **is mounted**:

> I:TWFunc::Set_Brightness: Setting brightness control to 255
> I:Set overlay: ''
> I:Set page: 'mount'
> I:Set page: 'decrypt'
> I:Set overlay: 'slideout'
> I:Set overlay: ''
> I:Set page: 'trydecrypt'
> I:operation_start: 'Decrypt'
> crypt_ftr->fs_size = 48627712
> Using scrypt with keymaster for cryptfs KDF
> WARNING: linker: /system/lib64/hw/keystore.default.so: unused DT entry: type 0x6ffffef5 arg 0x220
> WARNING: linker: /system/lib64/hw/keystore.default.so: unused DT entry: type 0x6ffffffe arg 0x4f0
> WARNING: linker: /system/lib64/hw/keystore.default.so: unused DT entry: type 0x6fffffff arg 0x1
> could not find any keystore module
> Failed to init keymaster
> Signing failed
> kdf failed
> failure decrypting master key
> Failed to decrypt master key
> crypt_ftr->fs_size = 48627712
> Using scrypt with keymaster for cryptfs KDF
> WARNING: linker: /system/lib64/hw/keystore.default.so: unused DT entry: type 0x6ffffef5 arg 0x220
> WARNING: linker: /system/lib64/hw/keystore.default.so: unused DT entry: type 0x6ffffffe arg 0x4f0
> WARNING: linker: /system/lib64/hw/keystore.default.so: unused DT entry: type 0x6fffffff arg 0x1
> could not find any keystore module
> Failed to init keymaster
> Signing failed
> kdf failed
> failure decrypting master key
> Failed to decrypt master key
> Failed to decrypt data.
> I:Set page: 'decrypt'
> I:operation_end - status=1

**Comment by steadfasterX** [comment] 2016-05-30 15:47
as far as I understood the decryption error is because the LG G4 uses hardware based encryption. At least this is mentioned in the configuration -> security menu..

So it should start working if someone (or I..) will rebuild a new TWRP version with hardware based encryption:

See: https://github.com/TeamWin/Team-Win-Recovery-Project/issues/323#issuecomment-191081069

See my request  @xda-forum: http://forum.xda-developers.com/showpost.php?p=67094629&postcount=422

**Comment by JohanLorenzo** [comment] 2016-07-12 06:57
Thanks @xdajog for the lead. I compiled twrp with `CONFIG_HW_DISK_ENCRYPTION := true` and `TARGET_HW_DISK_ENCRYPTION := true`, but there's likely something more to do to decrypt the master key.

recovery.log:

```
I:Copying file /cache/recovery/log to /cache/recovery/last_log
I:Is encrypted, do decrypt page first
I:Switching packages (TWRP)
I:Set page: 'decrypt'
I:Set page: 'trydecrypt'
I:operation_start: 'Decrypt'
crypt_ftr->fs_size = 48627712
Using scrypt with keymaster for cryptfs KDF
could not find any keystore module
Failed to init keymaster
Signing failed
kdf failed
failure decrypting master key
Failed to decrypt master key
crypt_ftr->fs_size = 48627712
Using scrypt with keymaster for cryptfs KDF
could not find any keystore module
Failed to init keymaster
Signing failed
kdf failed
failure decrypting master key
Failed to decrypt master key
Failed to decrypt data.
I:Set page: 'decrypt'
I:operation_end - status=1
I:Set page: 'main'
I:Set page: 'clear_vars'
I:Set page: 'main2'
I:Set page: 'main'
I:Set page: 'clear_vars'
I:Set page: 'main2'
I:Unable to mount settings storage during GUI startup.
I:Cannot load settings -- encrypted.
```

**Comment by steadfasterX** [comment] 2016-07-25 05:31
@JohanLorenzo: Too bad. could you provide or point to the full device tree you used? There are several around and I want to try it on my own.. 

~~Btw: 
I really missing some flags in your log!~~ (the flags I missed were removed in newer builds)

https://github.com/TeamWin/Team-Win-Recovery-Project/issues/484#issuecomment-172359397
E.g. has_hw_crypto etc..  
Could you check the mentioned tests and flags of the above link? 

Update: 
Since v3 of twrp the mentioned log entries I missed are not written anymore.

**Comment by steadfasterX** [comment] 2016-08-03 20:53
Ok I tested a LOT to get this fixed and I believe that both twrp flags may have nothing to do with the current issue we see here. 
~~I use a CM based Marshmallow 6.0.1 rom and I saw that in my case it seems that the device tree disables hardware based encryption when building CM.~~ Also when I look into the footer I see that I have aes cbc 256 in use which would be aes xts if it would be hardware based. ~~So both seems to show that at least in custom roms we have not hardware based encryption enabled. I'm not sure how to verify this for sure but if that is the case the twrp flags are contra productive.~~

**@All those having this issue:** 

Could you please provide 
- your android version (5.1.1, 6.0.1,...)
- using stock or custom 
- if custom please provide a link to the rom! (better its device tree)

**Comment by steadfasterX** [comment] 2016-08-04 18:45
Some progress:

> ~~Attempting to decrypt data partition via command line.
> crypt_ftr->fs_size = 48627712
> Using scrypt with keymaster for cryptfs KDF
> **keymaster module name is Keymaster QCOM HAL**
> keymaster version is 3
> Found keymaster0 module, using keymaster0 API.
> **Found keymaster0 module, using keymaster0 API.**
> could not open keymaster device in keystore (**Operation not permitted**)
> Failed to init keymaster
> Signing failed
> kdf failed
> failure decrypting master key
> Failed to decrypt master key~~

So what we can see here is that there are libraries needed which are normally not available within TWRP. I copied them manually and now I got the above success (a keystore can be found) ~~and the error regarding permission.~~
As far as I understood is that when keymaster comes into place it actually IS hardware backed encryption but well I may miss something here.
Nevertheless I will go on and I strongly believe that this issue can be solved - just wanted to let you know 

**Update:**
I made some more progress and now able to get the correct keymaster1 instead of 0. I'm also able to build all components (kernel, dtb image, twrp) on my own and most important complete based on marshmallow (omni rom)! If you like take a view on my device tree here at github. 
MM is required as build source because of some enhancements and fixes made in there to get the whole key master thingy working for us. 
Now I'm stuck at the next step in the decryption stage where qseecmd service comes into play. This one exits unconditionally atm and I try to figure out why. May be because of a selinux issue but we will see... Btw the support at twrp irc is great ;)

**Update2:**
There were several minor issues all could be solved with some time and patience but the main reason for the real looooong bug finding and trial & error over 75 builds (thanks strace! thanks strace! thanks strace!):
[pid   695] **readlinkat**(AT_FDCWD, "/**dev/block/bootdevice**", 0x7fcae70838, 1023) = -1 EINVAL (Invalid argument)
--> in (a little bit more) human readable:
a component responsible for communicating with the trusted keystore (rpmb) expects that /dev/block/bootdevice is a SYMLINK!!! if not it simply dies...
So I tried to fix that manually within twrp and tada.. I was able to **decrypt** !! 
I need to get the symlink automatically now (which is still not working) but when that is ready I will share the results of course. stay tuned.. we will get it decrypted ;) !

**Update 3:**
All news and updates here from now on: 
http://forum.xda-developers.com/g4/development/recovery-twrp-3-touch-recovery-t3442424/

**Comment by AdamWill** [comment] 2016-10-14 17:46
@steadfasterX thanks a lot for working on this; do you happen to know if the G3 case is the same or different from the G4 one?

**Comment by steadfasterX** [comment] 2016-10-15 15:11
@AdamWill: 
I don't know what issue you're referring to. Post the link and I can take a look on it. 

@bigbiff or @Dees_Troy :
Please close this issue as it is solved in 3.0.2-1 (for CM based ROMs)

**Comment by bigbiff** [comment] 2016-10-15 15:12
Thanks for verification @steadfasterX
Closing issue.

**Closed as completed by bigbiff** 2016-10-15 15:12 UTC

**Comment by AdamWill** [comment] 2016-10-15 23:28
@steadfasterX The LG G3 has what seems like the same problem: with standard TWRP builds, if you have a fairly recent version of Android (stock or CM, I think) and you encrypt the storage, TWRP can't decrypt it. I was wondering if you know whether the cause is the same for that model or not.

**Comment by steadfasterX** [comment] 2016-10-16 09:10
I think so. 
There were several issues preventing decryption in twrp. The main one is that you need the proprietary libs for decrypting..
