### ISSUE TITLE
TWRP 2.8.6.0 Unable to mount encrypted data on Nexus 7 wifi running 5.1

### ISSUE THREAD

**Issue by knyghtryda** [TeamWin/Team-Win-Recovery-Project#381] opened 2015-04-15 20:34 UTC
Mount fails with "twrp could not mount /data and unable to find crypto footer".  In 2.8.1.0 I get a password prompt but the password is not being recognized correctly.

**Comment by Ceremony64** [comment] 2015-04-19 23:25
Same issue here on a Galaxy Nexus and the Euphoria OS v1.1 ROM (5.1 AOSP base).
P.S. dupe of #323 #333 #358 and a few more

**Comment by iliaross** [comment] 2015-04-24 13:46
Same on HTC One M8

**Comment by bigbiff** [comment] 2018-08-19 18:51
No debug logs so closing.

**Closed as completed by bigbiff** 2018-08-19 18:51 UTC
