### ISSUE TITLE
n8013 2.3.3.0 Touchscreen issues

### ISSUE THREAD

**Issue by angel12** [TeamWin/Team-Win-Recovery-Project#88] opened 2013-01-18 22:32 UTC
The touchscreen only works about 25% of the time, once in a menu (like selecting a zip to flash) touching the screen usually leads to the device returning to the main home screen of twrp

**Comment by Dees-Troy** [comment] 2013-01-22 15:24
The Note 10.1 seems to have some touchscreen issues, as do a handful of other Samsung devices. I'm not sure what the cause is, but it's specific to those devices. TWRP works perfectly on the devices that I have in hand. Unfortunately no one in Team Win has a Note 10.1 which makes it very difficult for us to troubleshoot the problem. At best we could try a different kernel, but I'm not really sure if that will help or not.

**Comment by Dees-Troy** [comment] 2013-03-18 16:41
Closing because we are unable to provide a fix ourselves and no one in the community seems to be willing to help.

**Closed as completed by Dees-Troy** 2013-03-18 16:41 UTC
Labels: wontfix
