### ISSUE TITLE
Encryption on OnePlus One CM12 - TWRP 2.8.6 - Password Failed, Please Try Again

### ISSUE THREAD

**Issue by neoge** [TeamWin/Team-Win-Recovery-Project#394] opened 2015-05-04 17:44 UTC
Device: OnePlus One
OS: Cyanogen OS 12
My storage is encrypted. 
With CM11 KitKat i could access the storage with TWRP 2.8.6 when i entered my pw.
Now after the last update to CM12 based on Android 5.0 TWRP 2.8.6 cannot access the storage and output the error: Password Failed, Please Try Again

**Comment by jfeise** [comment] 2015-05-04 17:54
Duplicate. See https://github.com/TeamWin/Team-Win-Recovery-Project/issues/333

**Comment by Dees-Troy** [comment] 2015-05-18 16:17
This is a duplicate of 333. 333 is now resolved / closed. Closing this one as well.

**Closed as completed by Dees-Troy** 2015-05-18 16:17 UTC
