### ISSUE TITLE
TWRP 3.x performs zip signature verification even if the option is turned off

### ISSUE THREAD

**Issue by ghost** [TeamWin/Team-Win-Recovery-Project#1532] opened 2019-11-25 18:59 UTC
- [ x] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [ x] I am running the latest version of TWRP
- [ x] I have read the FAQ (https://twrp.me/FAQ/)
- [ x] I have searched for my issue and it does not already exist

**Device codename**: FP2
**TWRP version**: twrp-3.3.1-0-FP2.img

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
Booting into TWRP, I use 
    `adb sideload lineage-16.0-20191122-nightly-FP2-signed.zip`
to transfer the ROM to my phone. Alternatively, I've also moved the zip file to the internal storage and had TWRP find and install it via the menu options. For both methods, the checkbox "Zip signature verification" was unmarked.

#### WHAT IS THE EXPECTED RESULT?
The LineageOS ROM should be installed without zip file verification.

#### WHAT HAPPENS INSTEAD?
TWRP attempts zip file verification, which fails due to missing keys.

#### ADDITIONAL INFORMATION
I have tried different versions of TWRP down to twrp-3.1.0-0-fp2.img, as well as different builds from lineageOS, including old ones I've successfully installed on a different FP2 March this year. I've tried wiping data, cache and dalvik beforehand -  and once even the internal storage option that you get under "advanced wipe" in TWRP. Finally, I've set the Settings to default, rebooted and tried again, as well as checked if the zip signature verification option is reversed and tried sideloading with it checked.

`/tmp/recovery.log`: https://paste.omnirom.org/view/255fe07a
`dmesg`: https://paste.omnirom.org/view/5b78620c

**Comment by Jixi-Jou** [comment] 2019-12-22 21:45
Hi, same behavior here:

**Device codename**: FP2
**TWRP version**: twrp-3.3.1-1-FP2.img

**WHAT STEPS WILL REPRODUCE THE PROBLEM?**

Booting into TWRP, I find and install a .zip file of OpenGAPPS via the menu options. the checkbox "Zip signature verification" is unmarked. I also tried with the checkbox marked, and I also tried to mark the option in the settings to then perform the action of unmarking the checkbox before installing.

**WHAT IS THE EXPECTED RESULT?**

OpenGAPPS should be installed without zip file verification.

**WHAT HAPPENS INSTEAD?**

TWRP attempts zip file verification, which fails due to missing keys. The checkbox status does not seem to alter the way TWRP fails due to zip file verification (console content is identical).

**Comment by Jixi-Jou** [comment] 2019-12-27 21:36
I have finally bypassed the issue by accident while flashing and booting TWRP 3.3.1-1 with fastboot. I am new to these tools, but based on [this thread](https://forum.fairphone.com/t/complete-backup-tools-twrp-adb-and-others/23568/10) on fairphone forum, it seems that recovery behavior is different depending on the way you access it (either from fastboot or after an OS reboot)

**STEPS TO BYPASS THE ISSUE** (yet to be explained)

- Connect with ADB and execute `adb reboot bootloader`
- while in bootloader mode execute `fastboot flash recovery twrp-3.3.1-1-FP2.img`
- maintain the volume + button before sending `fastboot reboot` in order to boot directly to the newly flashed TWRP
- selecting a .zip file for install will show the checkbox for zip verification already checked (previous behavior was the checkbox being already unchecked), after unchecking the checkbox the installation proceeds normally without signature verification.

Hope this helps

**Comment by bigbiff** [comment] 2021-06-03 14:17
This was fixed in 3.5 series.

**Closed as completed by bigbiff** 2021-06-03 14:17 UTC
